<?php

namespace ContainerAWh4hhw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LLwoUV5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lLwoUV5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lLwoUV5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['privates', '.errored.RA.3uyq', NULL, 'Cannot determine controller argument for "App\\Controller\\InsertRecensementController::index()": the $em argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'habitantRepository' => ['privates', 'App\\Repository\\HabitantRepository', 'getHabitantRepositoryService', true],
        ], [
            'em' => '?',
            'habitantRepository' => 'App\\Repository\\HabitantRepository',
        ]);
    }
}
