<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKl6ARJP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKl6ARJP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKl6ARJP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKl6ARJP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKl6ARJP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kl6ARJP',
    'container.build_id' => '4bd4be9b',
    'container.build_time' => 1703176940,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKl6ARJP');
