<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLHxGZ5d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLHxGZ5d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLHxGZ5d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLHxGZ5d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLHxGZ5d\App_KernelDevDebugContainer([
    'container.build_hash' => 'LHxGZ5d',
    'container.build_id' => '3e4f199f',
    'container.build_time' => 1703264383,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLHxGZ5d');
