<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ81KJKG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ81KJKG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ81KJKG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ81KJKG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ81KJKG\App_KernelDevDebugContainer([
    'container.build_hash' => 'J81KJKG',
    'container.build_id' => '290b777f',
    'container.build_time' => 1703260685,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ81KJKG');
